backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

onEvent: node "/admin/cms.js"

collections:
  - name: buyititems
    label: Buy It Items
    format: yml
    extension: yml
    folder: data/buyititems/
    create: true
    slug: '{{title}}'
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Image, name: image, widget: image, required: true }
      - { label: Price, name: price, widget: number }
      - { label: Body, name: body, widget: markdown }

  - name: product
    label: Label
    format: yml
    extension: yml
    folder: data/products/
    create: true
    slug: '{{title}}'
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Image, name: image, widget: image, required: true }
      - { label: Lot, name: weight, widget: number }
      - { label: Current Price, name: price, widget: number }
      - { label: Body, name: body, widget: markdown }

  - name: blog
    label: Previous Auctions
    slug: '{{title}}'
    create: true
    files:
      - file: "source/posts/auction1.html.md"
        label: "Auction One"
        name: "lot1"
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - { label: Publish Date, name: date, widget: datetime }
          - { label: Body, name: body, widget: markdown }
          - label: Lot
            name: lotgroup
            widget: list
            fields:
              - label: Lot Number
                name: lotnumber
                widget: number
              - label: Description
                name: description
                widget: text
              - label: Image
                name: img
                widget: image
                required: false
              - label: Sold For
                name: price
                widget: string

  - name: page
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Carousel Images, name: carousel, widget: list, fields: [
                  { label: Image, name: image, widget: image },
                  { label: Caption, name: caption, widget: string }
                ] }
          - label: Story
            name: story
            widget: markdown
